# Generated by Django 5.0.4 on 2024-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Tag',
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(default='news.jpg', upload_to='pictures/'),
        ),
    ]
