# Generated by Django 5.0.4 on 2024-04-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='liked',
            new_name='likes',
        ),
    ]
